#!/usr/bin/env node

var program = require('commander'),
    fetch = require('./scripts/webrtc/fetch'),
    build = require('./scripts/webrtc/build');

program
  .version(require('./package.json').version)
  .option('-v, --verbose', 'output copious amounts of useful debug output when running');

program
  .command('fetch [branch]')
  .description('Fetch or update a specific branch of WebRTC')
  .action(fetch);

program
  .command('build [config]')
  .description('Build WebRTC using the desired config (Debug or Release)')
  .action(build);

program.parse(process.argv);
if (!program.args.length) program.help();